### ISSUE TITLE
Feature Suggestion: Add complete length of time to complete

### ISSUE THREAD

**Issue by johnnyperdomo** [ForrestKnight/open-source-cs#10]
You should add up all the weeks to completion from all the courses... useful to students who may want to know how long it takes to complete. 

_I counted a total of 198 weeks = 3.8 years_

**Example:**

- 198 weeks to Software Engineer 
- 4 year Computer Science Course
- 1386 days to Computer Engineer

**Comment by vintagesucks** [comment]
> I counted a total of 198 weeks = 3.8 years

This is only the case if you assume that you are doing one course at a time. You can work on courses from different sections in parallel.

**Comment by ronildo** [comment]
I like the idea of adding how long it would take
