### ISSUE TITLE
Suggestion / Request: Add Prerequisite: Pre-Calculus

### ISSUE THREAD

**Issue by weems** [ForrestKnight/open-source-cs#13]
Pre-Calculus is listed as a pre-requisite, it would be nice if there was a course linked to assist with preparing for Calculus Course[s].

**Comment by mknepper** [comment]
I'm open to this, but should we include lower level math curriculum too?

**Comment by leniquenoralez** [comment]
@weems  A great pre-calculus course would be [Pre-Calculus: Trigonometry](https://www.coursera.org/learn/trigonometry) on Coursera by UCI. Pre-Calculus is usually a combination of Trigonometry & Algebra. [Precalculus](https://en.wikipedia.org/wiki/Precalculus). I believe a precalculus course would suffice for lower level math as a pre-requisite. @mknepper  what would you consider lower level math?

**Comment by Alaharon123** [comment]
Two more good options are ASUx's on edX and Khan Academy
