### ISSUE TITLE
Why not Harvard's CS50?

### ISSUE THREAD

**Issue by agucova** [ForrestKnight/open-source-cs#14]
I recently finished HarvardX's Introduction to Computer Science ([CS50](https://www.edx.org/course/cs50s-introduction-computer-science-harvardx-cs50x)), and after doing a handful of MOOCs it really is the best course I've done, it has a huge and helpful community and the materials are amazing, not to mention the online lectures.

Some people might think using C in an introductory course is just an awful idea (and I did), but in retrospect, it gave me a low-level understanding before python that's incredibly useful, and they sure make it way easier than normal C courses.

I can totally suggest it as a replacement for Intro to CS by UVA.

**Comment by agucova** [comment]
It's the highest rating intro to cs course on [CourseCentral](https://www.class-central.com/course/edx-cs50-s-introduction-to-computer-science-442).

**Comment by duojet2ez** [comment]
> 
> 
> I recently finished HarvardX's Introduction to Computer Science ([CS50](https://www.edx.org/course/cs50s-introduction-computer-science-harvardx-cs50x)), and after doing a handful of MOOCs it really is the best course I've done, it has a huge and helpful community and the materials are amazing, not to mention the online lectures.
> 
> Some people might think using C in an introductory course is just an awful idea (and I did), but in retrospect, it gave me a low-level understanding before python that's incredibly useful, and they sure make it way easier than normal C courses.
> 
> I can totally suggest it as a replacement for Intro to CS by UVA.

@agucova From the reviews it appears quite difficult. How did you find it? Also, I would have to wait a few months before starting as I need to complete another course in c++... can I enroll whenever?

**Comment by agucova** [comment]
@duojet2ez yes, it is quite challenging (intellectually) and requires a significant time investment (as easy as it may appear when starting), but it is definitely doable, especially considering the great community around it. If you have doubts you can always use the StackOverflow  community or Reddit, or Discord....

You can start at any time since it renews it every year, importing any past evaluations, so if you don't get to finish the final project for this period, you can submit it for the next without any problem.

If you already started a C++ course, this may be a good complement considering it relies much more on the implementation of algorithms than the practical programming part.

**Comment by ForrestKnight** [comment]
Done
