### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by twocs** [ForrestKnight/open-source-cs#17]
> When a project is open source, that means anybody can view, use, modify, and distribute your project for any purpose. These permissions are enforced through an open source license. https://opensource.guide/starting-a-project/

As there is currently no license associated with the project, it is not an "Open Science" anything. The term "open source" is being used as clickbait and nothing more. However, this is easy to fix. Open source the project by doing the following: 

> No matter which stage you decide to open source your project, every project should include the following documentation:
> Open source license
> README
> Contributing guidelines
> Code of conduct
https://opensource.guide/starting-a-project/

Here is a list of the licenses that you might choose from: https://help.github.com/articles/licensing-a-repository/
Here is the steps on how to add the license to the repository: https://help.github.com/articles/adding-a-license-to-a-repository/

It's super easy and it will make "Open Source CS" open source.

**Comment by twocs** [comment]
See also https://github.com/ossu/computer-science for an example. The genius of open source universities is that you can, depending on the compatibility of the license terms, be able to build on their experience. In other words, you could literally copy-paste sections of their work into your own, as long as you comply with their licenses.

**Comment by snuggs** [comment]
@twocs shall we throw a PR together? I just got here from Youtube but looking for some low hanging fruit to help on. ;-) What say you?

P.S. I'm a GOpher as well. Great example ;-)

**Comment by twocs** [comment]
Sorry, @snuggs, didn't respond until now, but it does not seem appropriate to submit a pull request for a missing license. The copyright is owned by the creator and there are many different ways to license the work. Of course, if we knew which license the creator was thinking of, we could make a pull request on that basis.

**Comment by ForrestKnight** [comment]
Done. Thanks
