### ISSUE TITLE
The links are not opening

### ISSUE THREAD

**Issue by chankruze** [ForrestKnight/open-source-cs#18]
![screenshot 208](https://user-images.githubusercontent.com/29806845/52041025-38686f80-255f-11e9-90af-3532aa0bdfbc.png)

**Comment by gligorot** [comment]
Can you try again? Might have been a temporary server issue, seems fine from here.

**Comment by adagiox** [comment]
My pi-hole is blocking all the links

**Comment by chankruze** [comment]
@gligorot still issues for me.Let me try with VPN.
