### ISSUE TITLE
How do you want to receive suggestions?

### ISSUE THREAD

**Issue by then4p** [ForrestKnight/open-source-cs#19]
While I think this is great idea and the courses so far look great, it would be interesting how you would want to accept contributions.

e.g.: I feel like the 'Applications' area could use some more topics like security, computer graphics, embedded systems.

Usually after the basics, students like to dive into topics they're interested in, so that might help.

Great work!

**Comment by snuggs** [comment]
@then4p believe it or not you are already contributing. At minimum create an issue like you just did.
We use a guide over at *WHATWG* and *W3C* for new contributors. 

A perfect example of ISSUE / Pull Request flow that is trivial as a README.md is as follows:
Issue: https://github.com/whatwg/meta/issues/97
PR: https://github.com/whatwg/meta/pull/119

Example on what makes good contributions https://github.com/whatwg/meta/blob/master/COMMITTING.md

Hope this helps! /cc @ForrestKnight

**Comment by ForrestKnight** [comment]
Yea this is perfect. I've been neglecting contributions but going through everything now. I will do my best to stay on top of it so just open any issues or pull requests that you see fit.
