### ISSUE TITLE
Stupid Question: What license is this?

### ISSUE THREAD

**Issue by mknepper** [ForrestKnight/open-source-cs#22]
GPL? Creative Commons? Something custom?

**Comment by ashleydonald** [comment]
mknepper, the license is MIT, it's like creative commons.

**Comment by twocs** [comment]
I'm not sure how @ashleydonald concluded that it's an MIT license. As far as I can see there is no license associated with this repository. Furthermore, a list of other people's content is not software, so I'm not clear on what the MIT license would do.  Same issue: https://github.com/ForrestKnight/open-source-cs/issues/17#issuecomment-487247194

**Comment by AlexMunoz905** [comment]
I just don't think it has a license. It's just a document with a bunch of different courses for CS.

**Comment by twocs** [comment]
> I just don't think it has a license. It's just a document with a bunch of different courses for CS.

Isn't that the problem? There are currently 1241 forks of a document that has no explicit license. As a result, the copyright owner can impede and disrupt the integrity of every derivative work.

**Comment by mehmetkose** [comment]
This is just a list and includes open source projects. I don't get it why people look license something like this except Magazine editors who want to steal the whole list and make it own.

**Comment by ForrestKnight** [comment]
Added MIT license
