### ISSUE TITLE
Only 7-day free trial on coursera.

### ISSUE THREAD

**Issue by SamSep1ol** [ForrestKnight/open-source-cs#24]
When I try to enroll on course I only get the option to do a 7-day free trial and then pay 75 bucks a month. I thought it was supposed to be free?

**Comment by Dr-Passmore** [comment]
hey, 

Also received the same message. Been able to use it free for over a week. 

Should be ok.

**Comment by gamstc** [comment]
You should still be able to "audit" any Coursera course. This, however, will block access to some of the assignments and assessments (and of course the certificates) in some of the courses. 
![Screenshot 2019-03-19 at 14 11 33](https://user-images.githubusercontent.com/5268478/54608535-3300af00-4a51-11e9-8851-db31a7163f22.png)
