### ISSUE TITLE
cs open source in Portugues (Brasil)

### ISSUE THREAD

**Issue by wellingtonsilverio** [ForrestKnight/open-source-cs#25]
Does anyone know of something like this playlist only in Portuguese (Brazil) ?

**Comment by brunofbessa** [comment]
What do you mean? You want to watch the courses in Portuguese? The majority of platforms such as Coursera have Portuguese subtitles. If you want to know about PT-BR youtubers working with software development content you might want to check some these ones: Filipe Deschamps, Codigo Fonte TV, Rodrigo Souza, Programador BR, Filipe Alves and others. Peace.

**Comment by wellingtonsilverio** [comment]
I've heard of a videotape list that simulates a degree, which was done in Portuguese ... I would like to find it
