### ISSUE TITLE
edX paywall

### ISSUE THREAD

**Issue by gamstc** [ForrestKnight/open-source-cs#26]
Since the beginning of 2019 [edX is no longer giving free access to most of their courses](https://www.classcentral.com/report/edx-paywall-graded-assignments/), but "audit" access will now expire after a certain amount of time (sometimes as little as 2 days), unless you upgrade to the "verified track", which is of course paid. 

How does this affect your "open source" course list? If edX is no longer "open source", this list is significantly shrinked unfortunately. 😞

**Comment by AlexMunoz905** [comment]
Thanks for telling us. It sucks that they are doing that but, they gotta make money somehow.

**Comment by AlexMunoz905** [comment]
Whats the name of the course? I cant find edX on the list.

**Comment by gamstc** [comment]
edX is the platform where many of the courses on the list are hosted. 

BTW: Coursera is now also limiting free aka "audit" access for many courses and specializations. Bye bye, M*O*OCs 😞

**Comment by wonderbeaver** [comment]
So then no more free CS degrees. I guess it's GG on this repo.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/24/19,
10:52:26 PM

**Comment by ForrestKnight** [comment]
That hurts.

**Comment by ForrestKnight** [comment]
Actually, every single one of the edX courses in this curriculum are still free. I'm not sure the validity of Coursera limiting their audit access. Would you mind linking to where you saw that?

**Comment by meguimb** [comment]
They don't let you finish the course, some of them take x weeks to finish but before that they close your access to the course, I was talking about the Introduction to CS with Python on edx but i see you changed that one, don't know if it's the same for the others

**Comment by nunavailabul** [comment]
Isn't that just the MIT Open Courseware under the edX banner anyway(is free from MIT)?

**Comment by gamstc** [comment]
As I mentioned in my initial comment above, they changed their policy for _all_ courses in the beginning of the year (see the link I provided). [Here](https://support.edx.org/hc/en-us/articles/360013426233-How-long-can-I-access-a-course-in-the-audit-track-) is an explanation from their own Help Center.

**Comment by gamstc** [comment]
As for Coursera: [Here](https://coursera.community/community-help-questions-40/does-audit-mode-still-exist-644) is an example of a course that does not offer auditing anymore at all. In any case auditing always means you do not have access to assessments or even exercises (on edX *and* Coursera). And I would make the argument that the actual _learning_ happens when you solve exercises, not when you watch a free video, unfortunately. 😕

**Comment by johnwarmour** [comment]
> As I mentioned in my initial comment above, they changed their policy for _all_ courses in the beginning of the year (see the link I provided). [Here](https://support.edx.org/hc/en-us/articles/360013426233-How-long-can-I-access-a-course-in-the-audit-track-) is an explanation from their own Help Center.

From your link: "If the upgrade option no longer appears or if you do not wish to or are unable to pay, you may instead enroll again in a future session. "

Sounds like it's still free, you just change enrollment date.

**Comment by gamstc** [comment]
"A future session" on edX means a session that is likely to start within a year or two...

**Comment by gamstc** [comment]
[Here](https://www.classcentral.com/report/coursera-signup-for-free/) is another example about Coursera: If you look at the comment section, the latest comments from 2019 start describing more and more courses that don't offer the _audit_ option anymore.

**Comment by konradkusiak97** [comment]
Coursera offers usually only 7 days free, after that they require you to pay. Here, all the Java courses are like this. Except Programming languages A,B,C. Those seem to be for free.
