### ISSUE TITLE
Mathematics course

### ISSUE THREAD

**Issue by OJcoder17** [ForrestKnight/open-source-cs#27]
could you please add a precalculus

**Comment by jacksonb2913** [comment]
My favorite precalculus courses are
 https://modernstates.org/course/precalculus/ and https://www.edx.org/course/precalculus-asux-mat170x

**Comment by wonderbeaver** [comment]
I just finished taking the modernstates precalculus course.

The videos are good for condensed fast access to equations and principal
logic, but the textbook that comes with the course really lays out from
base to peak the concepts you need.
The negatives are the videos have some minor irritating bloopers, and of
the 90 or so questions at the end, I found just one that had an incorrect
solution. All in all I highly recommend. I am well ready for any
precalculus CLEP exam or test.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
03/25/19,
12:02:09 PM

**Comment by OJcoder17** [comment]
Thank you very much I appreciate it.

**Comment by ForrestKnight** [comment]
Done
