### ISSUE TITLE
Java Programming: Build a Recommendation System: Can't access course

### ISSUE THREAD

**Issue by JimmyXelectroN** [ForrestKnight/open-source-cs#29]
I can't access the course because it says i haven't finished the other course in specialization, which would require that I pay.

**Comment by gamstc** [comment]
That actually happens to most so called "Capstone Project" courses in Coursera specializations. Yet another reason why this list is not really "open-source" after all 😞. There are a lot of OER alternatives out there, though. I will try to come up with an actually open-source list at some point and share it here. 🚀
