### ISSUE TITLE
Just an idea: add subsection like cyber security?

### ISSUE THREAD

**Issue by wildaces215** [ForrestKnight/open-source-cs#3]
Forrest I love your vids! Just a suggestion why not add sections like cyber security? Would love to see it!

**Comment by Ibbanez** [comment]
Maybe that could be add on sections outside of the general premise.  I love the ideas.

**Comment by ForrestKnight** [comment]
I'm considering creating another repository for more specific sections, or dividing this repository into two sections. Section 1 is how it currently sits, and under that will be section 2 with the specific sections like AI dev, Cyber Security, Networking, etc.
