### ISSUE TITLE
Add * for suggested classes / branching sections

### ISSUE THREAD

**Issue by Christian-Ford** [ForrestKnight/open-source-cs#30]
I watched your video, and I get that it's for classes that you need to take for the degree, but maybe you could add classes (like the networking and cybersecurity) but have an * for the section or class to show that it's optional. This would also benefit in those that need to take the pre-cal or algebra like someone else mentioned.

Also I saw that it was a Java based curriculum , maybe have branching sections added for different paths, such as python or c, etc. By having a description under the Section header that links to the path you would rather take.

I really like the idea of the open source degree, but I feel it lacks a bit of diversity in options for the people who want to branch off a bit. I'm not sure if I am looking at it from a different viewpoint or not

**Comment by MrPilotMan** [comment]
A nice way to handle courses that branch off into different specialization areas, and keep the _degree_ motif intact, would be to put them in an "Electives" section and make the current courses the "Core".

In regards to other languages, possible multiple "Programming" sections representing "Tracks" could be added (i.e. Programming (Java Track), Programming (C++ track), Programming (Python Track)). They all cover the same material, but allow you to delve further into one language of your choice.
