### ISSUE TITLE
Use Python instead of Java?

### ISSUE THREAD

**Issue by anthonygedeon** [ForrestKnight/open-source-cs#34]
More Universities are using python because of the learning curve for students. We could possibly add alternatives to the programming courses.

**Comment by John-L-Jones-IV** [comment]
MIT's 6.0001 and 6.0002 use Python. Although the focus is on fundamentals not the language. I think that's a good thing.

**Comment by BangIAS** [comment]
I think it all depends on the policies of each university.
And if there is python in the learning material it is also better, because currently python is more widely used in the world of education as a support for basic understanding for data processing.

**Comment by THEnotSOgreatGUY** [comment]
Python and java should both be used. Python for more of a job oriented needs and java for greater understanding of programming,

**Comment by arthurnunesc** [comment]
There is already another list that changes all the Java courses to Python ones and adds the section Data Science, this addition is not necessary.

**Comment by gamstc** [comment]
Could you point me to that list @arthurnunesc ? 🙏

**Comment by arthurnunesc** [comment]
https://github.com/ForrestKnight/open-source-cs-python here it is.
