### ISSUE TITLE
Add Operating Systems Course?

### ISSUE THREAD

**Issue by namitoyokota** [ForrestKnight/open-source-cs#35]
Here are a couple of free courses that seems solid:
1. Coursera: [https://www.udacity.com/course/introduction-to-operating-systems--ud923](Coursera)
2. saylor.org: [https://learn.saylor.org/course/CS401](saylor.org)

**Comment by omarfahad** [comment]
Okay but ftu forum is mostly for udemy courses.  you need some operating
system You can check Unix or Linux courses there other many more courses
you can also check some courses on freecoursesite. If u want some
university courses then goto classcentral u will find many coursera courses.

Respect from,
Omar.
