### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by RobbyB97** [ForrestKnight/open-source-cs#41]
While this is an extremely useful resource (in my 7 years experience in learning to code, this is the best free resource I have encountered), you can only really peruse it through GitHub markdown in a slightly jarring, unresponsive table format. Putting this on a responsive, single page website with resources opening in a new tab might make it even better and accessible on any device. I have a React boilerplate, I can invest the time to do this. Thoughts?

**Comment by RobbyB97** [comment]
https://github.com/RobbyB97/open-source-cs/tree/website

**Comment by arthurnunesc** [comment]
I think that is a great idea.

**Comment by itzsrv** [comment]
I love the idea!

**Comment by RobbyB97** [comment]
https://github.com/RobbyB97/open-source-cs/tree/master It's a react app, based on https://github.com/robbyb97/reduxboilerplate ... I should have it done tomorrow

**Comment by RobbyB97** [comment]
It should be complete today, Forrest if you're reading this would you want to merge it and deploy the gh-pages yourself? It is just an npm run build:prod and git push to update it. I am not sure how gh-pages deploys work with a repo that multiple people work on. Please advise, thanks :D
