### ISSUE TITLE
A broken link 

### ISSUE THREAD

**Issue by Abdullah-Alhariri** [ForrestKnight/open-source-cs#60]
hey I noticed, when I visited the second link in the readme ([Mathematical Thinking in Computer Science](https://click.linksynergy.com/deeplink?id=PtFMiHYfEVk&mid=40328&murl=https%3A%2F%2Fwww.coursera.org%2Flearn%2Fwhat-is-a-proof)) it said "We were not able to find the page you're looking for"

**Comment by Reekeee** [comment]
It looks like that course was removed from coursera as the platform does not accept Russian content any longer.

Another user suggested these YouTube videos might be the same course:
[Link](https://www.youtube.com/watch?v=xG-gQIXwkX8)
[Link](https://www.youtube.com/watch?v=i8sphCg1yTs)
